import type { Metadata } from "next";
import "./globals.css";
import { Montserrat } from "next/font/google";
import ClientLayout from "@/components/layout/ClientLayout";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "600", "700", "800"],
  variable: "--font-montserrat",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Computational Intelligence Lab",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`h-full antialiased ${montserrat.variable}`}>
      <body className={montserrat.className}>
        <ClientLayout>
          {children}
        </ClientLayout>
      </body>
    </html>
  );
}